// Stephen King released written works for the bibliography explorer.
// Dates and work categories were checked against Stephen King's official Written Works list.
// Scope: released novels/novellas, story collections, nonfiction, and major coauthored books.
(() => {
  const SOURCE_URL = "https://stephenking.com/works/";

  function y(date) {
    return Number(String(date).slice(0, 4));
  }

  function work({
    id,
    title,
    date,
    type,
    summary,
    threads = [],
    places = [],
    links = [],
    themes = [],
    note = ""
  }) {
    return {
      id,
      title,
      written: date,
      writtenYear: y(date),
      published: date,
      publishedYear: y(date),
      venue: type,
      summary,
      entities: threads,
      locations: places,
      artifacts: links,
      themes,
      note,
      sourceUrl: SOURCE_URL
    };
  }

  window.STORIES = [
    work({
      id: "carrie",
      title: "Carrie",
      date: "1974-04-05",
      type: "Novel",
      summary: "King's debut turns a bullied teenager's telekinetic power into a tragedy of family abuse, school cruelty, and public humiliation.",
      threads: ["Maine", "Psychic powers", "Small-town evil"],
      places: ["Chamberlain, Maine"],
      links: ["Debut novel"],
      themes: ["Horror", "Coming of age", "Religious fanaticism"],
      note: "The first published Stephen King novel."
    }),
    work({
      id: "salems-lot",
      title: "'Salem's Lot",
      date: "1975-10-17",
      type: "Novel",
      summary: "A writer returns to a Maine town and finds an old house, a new antique dealer, and a spreading vampire infection hollowing the community from within.",
      threads: ["Maine", "Jerusalem's Lot", "Small-town evil"],
      places: ["Jerusalem's Lot, Maine"],
      links: ["Vampire novel"],
      themes: ["Horror", "Vampires", "Community decay"]
    }),
    work({
      id: "rage",
      title: "Rage",
      date: "1976-12",
      type: "Bachman Novel",
      summary: "A violent school hostage crisis becomes a grim psychological study of alienation, coercion, and teenage rage.",
      threads: ["Bachman", "Crime", "Controversial work"],
      places: ["Maine school"],
      links: ["Richard Bachman"],
      themes: ["Crime", "Psychological suspense", "School violence"],
      note: "Published under the Richard Bachman name and later allowed to go out of print."
    }),
    work({
      id: "the-shining",
      title: "The Shining",
      date: "1977-01",
      type: "Novel",
      summary: "A struggling writer takes his family to a snowed-in hotel, where his son's psychic gift exposes the building's hungry history.",
      threads: ["The Shining", "Psychic powers", "Family horror"],
      places: ["The Overlook Hotel", "Colorado"],
      links: ["Danny Torrance"],
      themes: ["Horror", "Haunted places", "Addiction"]
    }),
    work({
      id: "night-shift",
      title: "Night Shift",
      date: "1978-02",
      type: "Story Collection",
      summary: "King's first major collection gathers early nightmares of industrial terror, infected towns, haunted machinery, and ordinary places gone wrong.",
      threads: ["Story collection", "Maine", "Jerusalem's Lot"],
      places: ["Maine", "Small towns", "Workplaces"],
      links: ["First story collection"],
      themes: ["Horror", "Short fiction", "Blue-collar dread"]
    }),
    work({
      id: "the-stand",
      title: "The Stand",
      date: "1978-10",
      type: "Novel",
      summary: "After a military plague collapses civilization, survivors are pulled toward rival visions of rebuilding, faith, and domination.",
      threads: ["Apocalypse", "Randall Flagg", "Dark Tower connections"],
      places: ["Boulder", "Las Vegas", "United States"],
      links: ["Captain Trips"],
      themes: ["Post-apocalyptic", "Good and evil", "Epic horror"]
    }),
    work({
      id: "the-long-walk",
      title: "The Long Walk",
      date: "1978-12",
      type: "Bachman Novel",
      summary: "Teen boys enter a state-sponsored endurance contest where slowing down means execution and winning may be its own kind of ruin.",
      threads: ["Bachman", "Dystopia", "Road ordeal"],
      places: ["Maine", "American highways"],
      links: ["Richard Bachman"],
      themes: ["Dystopian fiction", "Survival", "Psychological suspense"]
    }),
    work({
      id: "the-dead-zone",
      title: "The Dead Zone",
      date: "1979-08",
      type: "Novel",
      summary: "A man awakens from a coma with psychic flashes and faces the moral burden of seeing a politician's catastrophic future.",
      threads: ["Castle Rock", "Psychic powers", "Political dread"],
      places: ["Castle Rock, Maine"],
      links: ["Johnny Smith"],
      themes: ["Supernatural", "Political thriller", "Fate"]
    }),
    work({
      id: "firestarter",
      title: "Firestarter",
      date: "1980-09-29",
      type: "Novel",
      summary: "A child with pyrokinetic power and her father flee a government agency that wants to weaponize the abilities it helped create.",
      threads: ["Psychic powers", "The Shop", "Family horror"],
      places: ["United States"],
      links: ["Charlie McGee"],
      themes: ["Science horror", "Conspiracy", "Parent and child"]
    }),
    work({
      id: "danse-macabre",
      title: "Danse Macabre",
      date: "1980-12",
      type: "Nonfiction",
      summary: "King surveys modern horror across books, film, radio, and television while arguing for why the genre's monsters endure.",
      threads: ["Nonfiction", "Writing craft", "Horror history"],
      places: ["Popular culture"],
      links: ["Critical nonfiction"],
      themes: ["Nonfiction", "Horror", "Cultural criticism"]
    }),
    work({
      id: "roadwork",
      title: "Roadwork",
      date: "1980-12",
      type: "Bachman Novel",
      summary: "A grieving man resists an urban highway project as the demolition of his neighborhood mirrors the collapse of his own life.",
      threads: ["Bachman", "Crime", "Ordinary breakdown"],
      places: ["Midwestern city"],
      links: ["Richard Bachman"],
      themes: ["Psychological suspense", "Grief", "Social pressure"]
    }),
    work({
      id: "cujo",
      title: "Cujo",
      date: "1981-09-08",
      type: "Novel",
      summary: "A rabid dog traps a mother and child in a broken-down car while Castle Rock's domestic fractures close in around them.",
      threads: ["Castle Rock", "Maine", "Family horror"],
      places: ["Castle Rock, Maine"],
      links: ["Castle Rock cycle"],
      themes: ["Horror", "Survival", "Domestic tension"]
    }),
    work({
      id: "the-running-man",
      title: "The Running Man",
      date: "1981-12",
      type: "Bachman Novel",
      summary: "In a brutal future economy, a desperate man joins a lethal television manhunt and becomes a threat to the spectacle itself.",
      threads: ["Bachman", "Dystopia", "Media satire"],
      places: ["Future United States"],
      links: ["Richard Bachman"],
      themes: ["Dystopian fiction", "Action thriller", "Class conflict"]
    }),
    work({
      id: "the-gunslinger",
      title: "The Dark Tower: The Gunslinger",
      date: "1982-06",
      type: "Novel",
      summary: "Roland Deschain crosses a dying desert in pursuit of the man in black, opening King's long western-fantasy quest for the Dark Tower.",
      threads: ["Dark Tower", "Roland Deschain", "Randall Flagg"],
      places: ["Mid-World", "Mohaine Desert"],
      links: ["Dark Tower I"],
      themes: ["Dark fantasy", "Quest", "Cosmic order"]
    }),
    work({
      id: "different-seasons",
      title: "Different Seasons",
      date: "1982-08",
      type: "Story Collection",
      summary: "Four novellas widen King's range into prison hope, corruption, childhood memory, and club-room ghost storytelling.",
      threads: ["Story collection", "Castle Rock", "Coming of age"],
      places: ["Maine", "Shawshank Prison"],
      links: ["Four novellas"],
      themes: ["Novellas", "Drama", "Crime"]
    }),
    work({
      id: "christine",
      title: "Christine",
      date: "1983-04-29",
      type: "Novel",
      summary: "A haunted 1958 Plymouth Fury consumes a lonely teenager's identity and turns high school jealousy into vehicular vengeance.",
      threads: ["Haunted object", "Coming of age", "Possession"],
      places: ["Pennsylvania"],
      links: ["Killer car"],
      themes: ["Horror", "Obsession", "Teen alienation"]
    }),
    work({
      id: "pet-sematary",
      title: "Pet Sematary",
      date: "1983-11",
      type: "Novel",
      summary: "A family discovers a burial ground that brings the dead back changed, making grief the doorway to a worse loss.",
      threads: ["Maine", "Family horror", "Ancient ground"],
      places: ["Ludlow, Maine"],
      links: ["Micmac burial ground"],
      themes: ["Horror", "Grief", "Resurrection"]
    }),
    work({
      id: "the-talisman",
      title: "The Talisman",
      date: "1984-11",
      type: "Novel",
      summary: "A boy crosses America and a parallel realm to find a talisman that may save his mother and another world's queen.",
      threads: ["Co-authored", "Peter Straub", "Dark Tower connections"],
      places: ["The Territories", "United States"],
      links: ["With Peter Straub"],
      themes: ["Dark fantasy", "Quest", "Parallel worlds"]
    }),
    work({
      id: "thinner",
      title: "Thinner",
      date: "1984-11",
      type: "Bachman Novel",
      summary: "A lawyer escapes punishment for a fatal accident, then wastes away under a curse that exposes the rot beneath respectability.",
      threads: ["Bachman", "Curse", "Crime"],
      places: ["Connecticut"],
      links: ["Richard Bachman"],
      themes: ["Horror", "Body horror", "Guilt"]
    }),
    work({
      id: "cycle-of-the-werewolf",
      title: "Cycle of the Werewolf",
      date: "1985-04",
      type: "Novel",
      summary: "A small Maine town is stalked month by month by a werewolf whose pattern turns the calendar into a countdown.",
      threads: ["Maine", "Small-town evil", "Creature horror"],
      places: ["Tarker's Mills, Maine"],
      links: ["Illustrated novel"],
      themes: ["Horror", "Werewolves", "Calendar structure"]
    }),
    work({
      id: "skeleton-crew",
      title: "Skeleton Crew",
      date: "1985-06",
      type: "Story Collection",
      summary: "A broad collection mixing monsters, apocalypse, science-fiction dread, and miniature terrors from King's early peak.",
      threads: ["Story collection", "Maine", "Apocalypse"],
      places: ["Maine", "Coasts", "Islands"],
      links: ["Includes The Mist"],
      themes: ["Horror", "Short fiction", "Science fiction"]
    }),
    work({
      id: "the-eyes-of-the-dragon",
      title: "The Eyes of the Dragon",
      date: "1987-02",
      type: "Novel",
      summary: "A fairy-tale kingdom is poisoned by court intrigue when Flagg frames a prince and bends royal succession toward chaos.",
      threads: ["Dark Tower connections", "Randall Flagg", "Dark fantasy"],
      places: ["Delain"],
      links: ["Flagg appearance"],
      themes: ["Fantasy", "Political intrigue", "Fairy tale"]
    }),
    work({
      id: "the-drawing-of-the-three",
      title: "The Dark Tower: The Drawing of the Three",
      date: "1987-05",
      type: "Novel",
      summary: "Roland draws companions from doorways into other lives, binding gunslinger fantasy to addiction, trauma, and modern America.",
      threads: ["Dark Tower", "Roland Deschain", "Ka-tet"],
      places: ["Mid-World", "New York"],
      links: ["Dark Tower II"],
      themes: ["Dark fantasy", "Quest", "Addiction"]
    }),
    work({
      id: "misery",
      title: "Misery",
      date: "1987-06",
      type: "Novel",
      summary: "A novelist is imprisoned by his biggest fan and forced to resurrect her favorite character under escalating threats.",
      threads: ["Writers in danger", "Captivity", "Fandom"],
      places: ["Colorado"],
      links: ["Paul Sheldon"],
      themes: ["Psychological horror", "Writing", "Obsession"]
    }),
    work({
      id: "the-tommyknockers",
      title: "The Tommyknockers",
      date: "1987-11",
      type: "Novel",
      summary: "A buried alien object transforms a Maine town into a feverish laboratory of invention, addiction, and bodily change.",
      threads: ["Maine", "Alien influence", "Small-town evil"],
      places: ["Haven, Maine"],
      links: ["Alien technology"],
      themes: ["Science horror", "Addiction", "Community corruption"]
    }),
    work({
      id: "nightmares-in-the-sky",
      title: "Nightmares in the Sky",
      date: "1987-12",
      type: "Nonfiction",
      summary: "King writes a horror-minded meditation on architectural gargoyles, treating stone monsters as cultural memory and warning.",
      threads: ["Nonfiction", "Horror history", "Visual culture"],
      places: ["Gothic architecture"],
      links: ["Photo commentary"],
      themes: ["Nonfiction", "Art", "Monsters"]
    }),
    work({
      id: "the-dark-half",
      title: "The Dark Half",
      date: "1989-11",
      type: "Novel",
      summary: "A writer's discarded pseudonym appears to become flesh, bringing murder and identity horror back to Castle Rock.",
      threads: ["Castle Rock", "Writers in danger", "Pseudonym"],
      places: ["Castle Rock, Maine"],
      links: ["Thad Beaumont"],
      themes: ["Horror", "Doppelganger", "Writing"]
    }),
    work({
      id: "four-past-midnight",
      title: "Four Past Midnight",
      date: "1990-09",
      type: "Story Collection",
      summary: "Four long stories explore time-eating creatures, a stolen identity, a predatory library figure, and a dangerous camera.",
      threads: ["Story collection", "Castle Rock", "Novellas"],
      places: ["Airports", "Maine", "Suburbs"],
      links: ["Four novellas"],
      themes: ["Horror", "Novellas", "Supernatural"]
    }),
    work({
      id: "the-waste-lands",
      title: "The Dark Tower: The Waste Lands",
      date: "1991-08",
      type: "Novel",
      summary: "Roland's ka-tet follows the Beam toward a ruined city and a sentient train with a taste for riddles.",
      threads: ["Dark Tower", "Roland Deschain", "Ka-tet"],
      places: ["Mid-World", "Lud"],
      links: ["Dark Tower III"],
      themes: ["Dark fantasy", "Quest", "Ruins"]
    }),
    work({
      id: "needful-things",
      title: "Needful Things",
      date: "1991-10",
      type: "Novel",
      summary: "A new shop in Castle Rock sells exactly what people want, charging secret acts that turn grudges into civic disaster.",
      threads: ["Castle Rock", "Small-town evil", "Temptation"],
      places: ["Castle Rock, Maine"],
      links: ["Leland Gaunt"],
      themes: ["Horror", "Satire", "Desire"]
    }),
    work({
      id: "geralds-game",
      title: "Gerald's Game",
      date: "1992-05",
      type: "Novel",
      summary: "Handcuffed to a bed after her husband's death, a woman fights dehydration, memory, and a possible figure in the room.",
      threads: ["Psychological survival", "Family trauma", "Maine"],
      places: ["Maine lake house"],
      links: ["Loose Dolores Claiborne connection"],
      themes: ["Psychological horror", "Survival", "Trauma"]
    }),
    work({
      id: "nightmares-and-dreamscapes",
      title: "Nightmares & Dreamscapes",
      date: "1993-10",
      type: "Story Collection",
      summary: "A large collection of horror, crime, fantasy, and oddities that shows King ranging across many forms and voices.",
      threads: ["Story collection", "Castle Rock", "Crime"],
      places: ["Maine", "London", "Roads"],
      links: ["Large collection"],
      themes: ["Horror", "Short fiction", "Crime"]
    }),
    work({
      id: "dolores-claiborne",
      title: "Dolores Claiborne",
      date: "1993-11",
      type: "Novel",
      summary: "A Maine housekeeper tells her life story in one fierce confession, revealing abuse, murder, and survival on Little Tall Island.",
      threads: ["Little Tall Island", "Maine", "Family trauma"],
      places: ["Little Tall Island, Maine"],
      links: ["Loose Gerald's Game connection"],
      themes: ["Psychological suspense", "Domestic abuse", "Voice-driven fiction"]
    }),
    work({
      id: "insomnia",
      title: "Insomnia",
      date: "1994-09",
      type: "Novel",
      summary: "An elderly widower in Derry begins seeing auras and hidden beings while a local political conflict opens onto cosmic stakes.",
      threads: ["Derry", "Dark Tower connections", "Psychic powers"],
      places: ["Derry, Maine"],
      links: ["Crimson King connection"],
      themes: ["Supernatural", "Aging", "Cosmic conflict"]
    }),
    work({
      id: "rose-madder",
      title: "Rose Madder",
      date: "1995-06",
      type: "Novel",
      summary: "A woman escapes an abusive husband and is pulled through a painting into a mythic landscape that gives her fear a shape.",
      threads: ["Family trauma", "Dark fantasy", "Escape"],
      places: ["Midwestern city", "Painted world"],
      links: ["Mythic painting"],
      themes: ["Fantasy horror", "Domestic abuse", "Transformation"]
    }),
    work({
      id: "the-regulators",
      title: "The Regulators",
      date: "1995-12",
      type: "Bachman Novel",
      summary: "A suburban street becomes a lethal pop-culture western under the control of a possessed child and an alien force.",
      threads: ["Bachman", "Desperation mirror", "Possession"],
      places: ["Ohio suburb"],
      links: ["Paired with Desperation"],
      themes: ["Horror", "Suburban dread", "Reality distortion"]
    }),
    work({
      id: "the-green-mile",
      title: "The Green Mile",
      date: "1996-03",
      type: "Serial Novel",
      summary: "Death-row guards encounter John Coffey, a condemned man with impossible healing power and a terrible burden of innocence.",
      threads: ["Prison", "Supernatural gift", "Serial publication"],
      places: ["Cold Mountain Penitentiary"],
      links: ["Published in six installments"],
      themes: ["Supernatural", "Crime", "Mercy"],
      note: "Originally released as a six-part serial novel in 1996."
    }),
    work({
      id: "desperation",
      title: "Desperation",
      date: "1996-09-24",
      type: "Novel",
      summary: "Travelers trapped in a Nevada mining town face a possessed sheriff and an ancient force speaking through human bodies.",
      threads: ["Desperation mirror", "Dark Tower connections", "Possession"],
      places: ["Desperation, Nevada"],
      links: ["Paired with The Regulators"],
      themes: ["Horror", "Faith", "Ancient evil"]
    }),
    work({
      id: "wizard-and-glass",
      title: "The Dark Tower: Wizard and Glass",
      date: "1997-11",
      type: "Novel",
      summary: "Roland recounts his doomed first love in Mejis while the ka-tet moves through a world echoing The Stand.",
      threads: ["Dark Tower", "Roland Deschain", "Randall Flagg"],
      places: ["Mid-World", "Mejis", "Topeka"],
      links: ["Dark Tower IV"],
      themes: ["Dark fantasy", "Romance", "Tragedy"]
    }),
    work({
      id: "bag-of-bones",
      title: "Bag of Bones",
      date: "1998-09-22",
      type: "Novel",
      summary: "A blocked widower returns to a haunted lake house and uncovers a buried history of violence tied to his family.",
      threads: ["Maine", "Writers in danger", "Haunted places"],
      places: ["TR-90, Maine"],
      links: ["Scribner era"],
      themes: ["Ghost story", "Grief", "Secrets"]
    }),
    work({
      id: "the-girl-who-loved-tom-gordon",
      title: "The Girl Who Loved Tom Gordon",
      date: "1999-04",
      type: "Novel",
      summary: "A lost girl survives the woods by listening to Red Sox broadcasts while something real or imagined follows her.",
      threads: ["Maine", "Survival", "Child protagonist"],
      places: ["Appalachian Trail", "Maine woods"],
      links: ["Baseball motif"],
      themes: ["Survival", "Psychological suspense", "Nature horror"]
    }),
    work({
      id: "hearts-in-atlantis",
      title: "Hearts in Atlantis",
      date: "1999-09",
      type: "Story Collection",
      summary: "Linked stories move from childhood in 1960 to Vietnam-era damage and adult aftermath, with one strand tied to the Dark Tower mythos.",
      threads: ["Story collection", "Dark Tower connections", "Coming of age"],
      places: ["Connecticut", "University of Maine", "Vietnam-era America"],
      links: ["Low Men connection"],
      themes: ["Linked stories", "Memory", "Loss of innocence"]
    }),
    work({
      id: "on-writing",
      title: "On Writing: A Memoir of the Craft",
      date: "1999-12",
      type: "Nonfiction",
      summary: "Part memoir and part practical manual, King's best-known craft book explains his working habits, toolbox, and recovery after the 1999 accident.",
      threads: ["Nonfiction", "Writing craft", "Memoir"],
      places: ["Maine", "Writing desk"],
      links: ["Craft guide"],
      themes: ["Nonfiction", "Memoir", "Writing"]
    }),
    work({
      id: "secret-windows",
      title: "Secret Windows",
      date: "1999-12",
      type: "Nonfiction",
      summary: "A companion volume of essays, speeches, interviews, and fiction centered on King's views of reading, writing, and genre.",
      threads: ["Nonfiction", "Writing craft", "Essays"],
      places: ["Writing life"],
      links: ["Craft essays"],
      themes: ["Nonfiction", "Writing", "Collected prose"]
    }),
    work({
      id: "dreamcatcher",
      title: "Dreamcatcher",
      date: "2001-02-20",
      type: "Novel",
      summary: "Friends with a childhood psychic bond reunite in the Maine woods just as an alien infection and military containment arrive.",
      threads: ["Maine", "Psychic powers", "Alien influence"],
      places: ["Derry, Maine", "Jefferson Tract"],
      links: ["Derry reference"],
      themes: ["Science horror", "Friendship", "Invasion"]
    }),
    work({
      id: "black-house",
      title: "Black House",
      date: "2001-09-15",
      type: "Novel",
      summary: "Jack Sawyer, now retired from police work, is pulled back into a child-murder case with direct links to the Territories and the Dark Tower.",
      threads: ["Co-authored", "Peter Straub", "Dark Tower connections"],
      places: ["Wisconsin", "The Territories"],
      links: ["Sequel to The Talisman"],
      themes: ["Dark fantasy", "Crime", "Parallel worlds"]
    }),
    work({
      id: "everythings-eventual",
      title: "Everything's Eventual",
      date: "2002-03",
      type: "Story Collection",
      summary: "A collection balancing horror, crime, and uncanny gifts, including a Dark Tower story and several later adaptation favorites.",
      threads: ["Story collection", "Dark Tower connections", "Psychic powers"],
      places: ["Maine", "Roads", "Hotels"],
      links: ["Includes The Little Sisters of Eluria"],
      themes: ["Horror", "Short fiction", "Supernatural"]
    }),
    work({
      id: "from-a-buick-8",
      title: "From a Buick 8",
      date: "2002-09-24",
      type: "Novel",
      summary: "Pennsylvania troopers guard a not-quite-car that behaves like a portal to something alien and unknowable.",
      threads: ["Alien influence", "Haunted object", "Police"],
      places: ["Pennsylvania barracks"],
      links: ["Strange vehicle"],
      themes: ["Science horror", "Mystery", "Cosmic dread"]
    }),
    work({
      id: "wolves-of-the-calla",
      title: "The Dark Tower: Wolves of the Calla",
      date: "2003-11",
      type: "Novel",
      summary: "Roland's ka-tet defends a border town from masked raiders while King's multiverse folds more openly into the quest.",
      threads: ["Dark Tower", "Roland Deschain", "Ka-tet"],
      places: ["Calla Bryn Sturgis", "Mid-World"],
      links: ["Dark Tower V"],
      themes: ["Dark fantasy", "Western", "Community defense"]
    }),
    work({
      id: "song-of-susannah",
      title: "The Dark Tower: Song of Susannah",
      date: "2004-06",
      type: "Novel",
      summary: "The ka-tet splits across worlds as Susannah's pregnancy and the series' metafictional stakes rush toward the Tower.",
      threads: ["Dark Tower", "Ka-tet", "Metafiction"],
      places: ["New York", "Maine", "Mid-World"],
      links: ["Dark Tower VI"],
      themes: ["Dark fantasy", "Metafiction", "Identity"]
    }),
    work({
      id: "the-dark-tower",
      title: "The Dark Tower",
      date: "2004-09",
      type: "Novel",
      summary: "Roland's quest reaches the Tower after loss, revelation, and a final confrontation with the cost of obsession.",
      threads: ["Dark Tower", "Roland Deschain", "Crimson King"],
      places: ["End-World", "The Dark Tower"],
      links: ["Dark Tower VII"],
      themes: ["Dark fantasy", "Quest", "Recurrence"]
    }),
    work({
      id: "faithful",
      title: "Faithful",
      date: "2005-09",
      type: "Nonfiction",
      summary: "King and Stewart O'Nan chronicle the Boston Red Sox 2004 season with the emotional pacing of lifelong fans watching history change.",
      threads: ["Nonfiction", "Co-authored", "Baseball"],
      places: ["Boston", "Fenway Park"],
      links: ["With Stewart O'Nan"],
      themes: ["Nonfiction", "Sports", "Diary"]
    }),
    work({
      id: "the-colorado-kid",
      title: "The Colorado Kid",
      date: "2005-10",
      type: "Novel",
      summary: "Two old newspapermen and an intern circle an unsolved corpse-on-a-beach mystery that resists clean answers.",
      threads: ["Hard Case Crime", "Maine", "Mystery"],
      places: ["Moose-Lookit Island, Maine"],
      links: ["Hard Case Crime"],
      themes: ["Crime", "Mystery", "Unresolved questions"]
    }),
    work({
      id: "cell",
      title: "Cell",
      date: "2006-01-24",
      type: "Novel",
      summary: "A signal sent through mobile phones turns ordinary people into violent, evolving flocks while survivors search for family.",
      threads: ["Apocalypse", "Technology dread", "Family quest"],
      places: ["Boston", "New England"],
      links: ["Pulse event"],
      themes: ["Post-apocalyptic", "Technology horror", "Survival"]
    }),
    work({
      id: "liseys-story",
      title: "Lisey's Story",
      date: "2006-10",
      type: "Novel",
      summary: "A widow sorts through her novelist husband's papers and private language, uncovering a dangerous inner world behind his work.",
      threads: ["Writers in danger", "Family horror", "Boo'ya Moon"],
      places: ["Maine", "Boo'ya Moon"],
      links: ["Scott Landon"],
      themes: ["Dark fantasy", "Marriage", "Grief"]
    }),
    work({
      id: "blaze",
      title: "Blaze",
      date: "2006-12",
      type: "Bachman Novel",
      summary: "A damaged small-time criminal kidnaps a baby and stumbles into a doomed, strangely tender crime story.",
      threads: ["Bachman", "Crime", "Outsider"],
      places: ["New England"],
      links: ["Richard Bachman"],
      themes: ["Crime", "Tragedy", "Loneliness"]
    }),
    work({
      id: "duma-key",
      title: "Duma Key",
      date: "2008-01-22",
      type: "Novel",
      summary: "After a catastrophic injury, a man moves to a Florida island where his paintings open a channel to a buried supernatural force.",
      threads: ["Haunted places", "Art", "Recovery"],
      places: ["Duma Key, Florida"],
      links: ["Paintings"],
      themes: ["Horror", "Art", "Healing and danger"]
    }),
    work({
      id: "just-after-sunset",
      title: "Just After Sunset",
      date: "2008-11",
      type: "Story Collection",
      summary: "A collection of late-2000s stories about mortality, revenge, accidents, and uncanny interruptions in everyday life.",
      threads: ["Story collection", "Maine", "Everyday dread"],
      places: ["Florida", "Maine", "Roads"],
      links: ["Modern collection"],
      themes: ["Horror", "Short fiction", "Mortality"]
    }),
    work({
      id: "stephen-king-goes-to-the-movies",
      title: "Stephen King Goes to the Movies",
      date: "2009-01",
      type: "Story Collection",
      summary: "A film-focused collection gathers five previously published stories that became movies, with King's introductions framing their adaptations.",
      threads: ["Story collection", "Adaptations", "Film"],
      places: ["Various"],
      links: ["Adaptation-focused reprint collection"],
      themes: ["Short fiction", "Film", "Retrospective"],
      note: "Included as a collection with new author commentary, though the stories were previously published."
    }),
    work({
      id: "under-the-dome",
      title: "Under the Dome",
      date: "2009-11",
      type: "Novel",
      summary: "An invisible barrier seals a Maine town from the world, letting civic corruption, panic, and authoritarian instincts accelerate.",
      threads: ["Maine", "Small-town evil", "Political dread"],
      places: ["Chester's Mill, Maine"],
      links: ["Town under barrier"],
      themes: ["Science fiction", "Political thriller", "Community breakdown"]
    }),
    work({
      id: "blockade-billy",
      title: "Blockade Billy",
      date: "2010-04-20",
      type: "Novella",
      summary: "An old baseball hand recounts the brief, disturbing career of a catcher whose legend was erased from the record.",
      threads: ["Baseball", "Crime", "Novella"],
      places: ["Baseball circuit"],
      links: ["Standalone novella"],
      themes: ["Crime", "Sports", "Tall tale"]
    }),
    work({
      id: "full-dark-no-stars",
      title: "Full Dark, No Stars",
      date: "2010-11",
      type: "Story Collection",
      summary: "Four bleak novellas focus on secret violence, revenge, guilt, and the ugly bargains people make with themselves.",
      threads: ["Story collection", "Novellas", "Crime"],
      places: ["Nebraska", "Maine", "American towns"],
      links: ["Four novellas"],
      themes: ["Crime", "Psychological horror", "Moral darkness"]
    }),
    work({
      id: "11-22-63",
      title: "11/22/63",
      date: "2011-11-08",
      type: "Novel",
      summary: "A teacher travels through a Maine time portal to stop the Kennedy assassination and discovers how violently history resists change.",
      threads: ["Time travel", "Maine", "Derry"],
      places: ["Maine", "Derry", "Dallas"],
      links: ["Kennedy assassination"],
      themes: ["Historical fiction", "Time travel", "Romance"]
    }),
    work({
      id: "wind-through-the-keyhole",
      title: "The Dark Tower: The Wind Through the Keyhole",
      date: "2012-04",
      type: "Novel",
      summary: "A nested tale set within Roland's journey adds a storm-bound fable to the Dark Tower cycle.",
      threads: ["Dark Tower", "Roland Deschain", "Story within story"],
      places: ["Mid-World"],
      links: ["Dark Tower interlude"],
      themes: ["Dark fantasy", "Fairy tale", "Memory"]
    }),
    work({
      id: "guns",
      title: "Guns",
      date: "2013-01",
      type: "Nonfiction",
      summary: "A short nonfiction essay lays out King's argument after the Sandy Hook shooting and reflects on violence, culture, and responsibility.",
      threads: ["Nonfiction", "Essay", "Political dread"],
      places: ["United States"],
      links: ["Kindle essay"],
      themes: ["Nonfiction", "Gun violence", "Public argument"]
    }),
    work({
      id: "joyland",
      title: "Joyland",
      date: "2013-06",
      type: "Novel",
      summary: "A college student working at a coastal amusement park is drawn into a murder mystery, a ghost story, and first heartbreak.",
      threads: ["Hard Case Crime", "Coming of age", "Ghost story"],
      places: ["North Carolina amusement park"],
      links: ["Hard Case Crime"],
      themes: ["Crime", "Coming of age", "Melancholy"]
    }),
    work({
      id: "doctor-sleep",
      title: "Doctor Sleep",
      date: "2013-09-24",
      type: "Novel",
      summary: "Adult Danny Torrance, scarred by the Overlook and addiction, protects a powerful girl from psychic predators.",
      threads: ["The Shining", "Psychic powers", "Family horror"],
      places: ["New Hampshire", "American roads"],
      links: ["Sequel to The Shining"],
      themes: ["Horror", "Recovery", "Psychic vampires"]
    }),
    work({
      id: "mr-mercedes",
      title: "Mr. Mercedes",
      date: "2014-06",
      type: "Novel",
      summary: "Retired detective Bill Hodges is taunted by a mass murderer, pushing King into a hard-edged crime trilogy.",
      threads: ["Bill Hodges", "Holly Gibney", "Crime"],
      places: ["Midwestern city"],
      links: ["Bill Hodges trilogy I"],
      themes: ["Crime", "Thriller", "Obsession"]
    }),
    work({
      id: "revival",
      title: "Revival",
      date: "2014-11",
      type: "Novel",
      summary: "A boy's lifelong connection with a preacher obsessed with secret electricity leads toward one of King's bleakest cosmic revelations.",
      threads: ["Maine", "Cosmic horror", "Obsession"],
      places: ["Maine", "Touring circuits"],
      links: ["Secret electricity"],
      themes: ["Horror", "Faith", "Afterlife dread"]
    }),
    work({
      id: "finders-keepers",
      title: "Finders Keepers",
      date: "2015-06-02",
      type: "Novel",
      summary: "A murdered author's hidden notebooks entangle a young reader, an ex-con, and Bill Hodges' investigative circle.",
      threads: ["Bill Hodges", "Holly Gibney", "Writers in danger"],
      places: ["Midwestern city"],
      links: ["Bill Hodges trilogy II"],
      themes: ["Crime", "Literary obsession", "Thriller"]
    }),
    work({
      id: "bazaar-of-bad-dreams",
      title: "The Bazaar of Bad Dreams",
      date: "2015-11",
      type: "Story Collection",
      summary: "King pairs stories with brief notes on their origins, creating a curated shopfront of mortality, guilt, and weird turns.",
      threads: ["Story collection", "Writing craft", "Everyday dread"],
      places: ["Various"],
      links: ["Author notes"],
      themes: ["Horror", "Short fiction", "Mortality"]
    }),
    work({
      id: "end-of-watch",
      title: "End of Watch",
      date: "2016-06-07",
      type: "Novel",
      summary: "The Hodges trilogy closes as Brady Hartsfield's violence mutates from crime into a more supernatural threat.",
      threads: ["Bill Hodges", "Holly Gibney", "Psychic powers"],
      places: ["Midwestern city"],
      links: ["Bill Hodges trilogy III"],
      themes: ["Crime", "Supernatural thriller", "Legacy"]
    }),
    work({
      id: "gwendys-button-box",
      title: "Gwendy's Button Box",
      date: "2017-05-16",
      type: "Novella",
      summary: "A girl in Castle Rock receives a mysterious box whose buttons suggest impossible power and terrible responsibility.",
      threads: ["Gwendy Peterson", "Castle Rock", "Co-authored"],
      places: ["Castle Rock, Maine"],
      links: ["With Richard Chizmar"],
      themes: ["Dark fantasy", "Coming of age", "Temptation"]
    }),
    work({
      id: "sleeping-beauties",
      title: "Sleeping Beauties",
      date: "2017-09-26",
      type: "Novel",
      summary: "Women across the world fall into cocooned sleep, leaving men to confront fear, violence, and a changed order.",
      threads: ["Co-authored", "Owen King", "Apocalypse"],
      places: ["Appalachian town"],
      links: ["With Owen King"],
      themes: ["Speculative fiction", "Gender", "Social collapse"]
    }),
    work({
      id: "the-outsider",
      title: "The Outsider",
      date: "2018-05",
      type: "Novel",
      summary: "An impossible murder case brings Holly Gibney into contact with a predator that wears human evidence like a mask.",
      threads: ["Holly Gibney", "Crime", "Supernatural predator"],
      places: ["Oklahoma", "Texas"],
      links: ["Holly Gibney novel"],
      themes: ["Crime", "Horror", "Identity"]
    }),
    work({
      id: "elevation",
      title: "Elevation",
      date: "2018-10-30",
      type: "Novella",
      summary: "A Castle Rock man steadily loses weight without changing size, using his strange condition to change a town's resentments.",
      threads: ["Castle Rock", "Novella", "Small-town evil"],
      places: ["Castle Rock, Maine"],
      links: ["Castle Rock novella"],
      themes: ["Speculative fiction", "Community", "Grace"]
    }),
    work({
      id: "the-institute",
      title: "The Institute",
      date: "2019-09",
      type: "Novel",
      summary: "Psychically gifted children are imprisoned and exploited by a secret organization until escape becomes rebellion.",
      threads: ["Psychic powers", "The Shop echoes", "Child protagonists"],
      places: ["Maine", "Secret facility"],
      links: ["Gifted children"],
      themes: ["Science horror", "Institutional cruelty", "Resistance"]
    }),
    work({
      id: "if-it-bleeds",
      title: "If It Bleeds",
      date: "2020-04",
      type: "Story Collection",
      summary: "Four novellas include a major Holly Gibney case and meditations on friendship, art, bargains, and late-life reckoning.",
      threads: ["Story collection", "Holly Gibney", "Novellas"],
      places: ["Maine", "Pennsylvania", "Midwestern city"],
      links: ["Includes If It Bleeds"],
      themes: ["Novellas", "Crime", "Supernatural"]
    }),
    work({
      id: "later",
      title: "Later",
      date: "2021-03-02",
      type: "Novel",
      summary: "A boy who can speak with the newly dead becomes entangled in crime, family secrets, and one haunting that refuses to fade.",
      threads: ["Hard Case Crime", "Psychic powers", "Child protagonist"],
      places: ["New York"],
      links: ["Hard Case Crime"],
      themes: ["Crime", "Supernatural", "Coming of age"]
    }),
    work({
      id: "billy-summers",
      title: "Billy Summers",
      date: "2021-08-03",
      type: "Novel",
      summary: "A hitman posing as a writer takes one last job, then turns against the people who tried to use him.",
      threads: ["Crime", "Writers in danger", "Road story"],
      places: ["American South", "Colorado"],
      links: ["Crime novel"],
      themes: ["Crime", "Identity", "Redemption"]
    }),
    work({
      id: "gwendys-final-task",
      title: "Gwendy's Final Task",
      date: "2022-02-15",
      type: "Novel",
      summary: "Gwendy Peterson carries the button box into a final mission that reaches beyond Earth and back into Castle Rock history.",
      threads: ["Gwendy Peterson", "Castle Rock", "Co-authored"],
      places: ["Castle Rock, Maine", "Space station"],
      links: ["With Richard Chizmar"],
      themes: ["Dark fantasy", "Responsibility", "Finale"]
    }),
    work({
      id: "fairy-tale",
      title: "Fairy Tale",
      date: "2022-09-06",
      type: "Novel",
      summary: "A teenager inherits a key to a hidden world where fairy-tale wonder, disease, and tyranny wait below an old man's property.",
      threads: ["Dark fantasy", "Coming of age", "Portal world"],
      places: ["Illinois", "Empis"],
      links: ["Portal fantasy"],
      themes: ["Fantasy", "Quest", "Good and evil"]
    }),
    work({
      id: "holly",
      title: "Holly",
      date: "2023-09-05",
      type: "Novel",
      summary: "Holly Gibney investigates disappearances tied to an outwardly respectable couple and a private horror of appetite and control.",
      threads: ["Holly Gibney", "Crime", "Serial killers"],
      places: ["Midwestern city"],
      links: ["Holly Gibney novel"],
      themes: ["Crime", "Psychological horror", "Investigation"]
    }),
    work({
      id: "you-like-it-darker",
      title: "You Like It Darker",
      date: "2024-05",
      type: "Story Collection",
      summary: "A late-career collection leans into mortality, uncanny bargains, returning shadows, and the long reach of old sins.",
      threads: ["Story collection", "Maine", "Late work"],
      places: ["Florida", "Maine", "American towns"],
      links: ["Recent collection"],
      themes: ["Horror", "Short fiction", "Mortality"]
    }),
    work({
      id: "never-flinch",
      title: "Never Flinch",
      date: "2025-05-27",
      type: "Novel",
      summary: "A recent Holly Gibney-era thriller follows intertwined threats, obsession, and investigation in King's continuing crime-horror lane.",
      threads: ["Holly Gibney", "Crime", "Late work"],
      places: ["United States"],
      links: ["Recent novel"],
      themes: ["Crime", "Thriller", "Horror"],
      note: "Latest released novel included in this working copy as of June 17, 2026."
    })
  ];
})();
