window.MALLORY_EVENTS = [
  { id:"recon", date:"1921", sort:"1921-09-01T12:00", time:"Autumn", title:"The northern approach is mapped", altitude:"c. 7,000 m", camp:"North Col", type:"document", certainty:"documented", people:"Mallory · Bullock · Wheeler", summary:"The first British reconnaissance identifies the East Rongbuk Glacier and North Col as a workable line toward Everest’s northeast ridge.", source:"RGS / Merton College Everest timeline" },
  { id:"1922", date:"May 1922", sort:"1922-05-21T12:00", time:"Expedition season", title:"First sustained summit attempts", altitude:"8,225 m", camp:"North ridge", type:"document", certainty:"documented", people:"Mallory · Norton · Somervell", summary:"The 1922 party climbs without oxygen to roughly 8,225 metres. A later oxygen-assisted party reaches about 8,321 metres; an avalanche kills seven porters.", source:"Alpine Journal / RGS" },
  { id:"arrive", date:"29 Apr 1924", sort:"1924-04-29T12:00", time:"Afternoon", title:"Base Camp established", altitude:"c. 5,150 m", camp:"Base Camp", type:"document", certainty:"documented", people:"1924 expedition", summary:"After the long approach across Tibet, the party establishes Base Camp on the Rongbuk Glacier and begins carrying loads toward the North Col.", source:"1924 expedition dispatches" },
  { id:"norton", date:"4 Jun 1924", sort:"1924-06-04T12:00", time:"c. 13:00", title:"Norton sets an altitude record", altitude:"c. 8,573 m", camp:"Great Couloir", type:"document", certainty:"documented", people:"Edward Norton · Howard Somervell", summary:"Climbing without bottled oxygen, Norton traverses into the Great Couloir and reaches about 8,573 metres before turning back—an altitude record that stands until 1952.", source:"Norton, The Fight for Everest" },
  { id:"camp4", date:"6 Jun 1924", sort:"1924-06-06T07:30", time:"07:30", title:"Mallory and Irvine leave Camp IV", altitude:"c. 7,010 m", camp:"Camp IV · North Col", type:"photo", certainty:"documented", people:"Mallory · Irvine · Odell", summary:"Noel Odell photographs the pair leaving the North Col with porters, oxygen apparatus and supplies for their high camps—the last close photographs of them.", source:"Merton College / RGS timeline" },
  { id:"camp5", date:"7 Jun 1924", sort:"1924-06-07T08:00", time:"Morning", title:"Porters descend from Camp V", altitude:"c. 7,680 m", camp:"Camp V", type:"testimony", certainty:"documented", people:"Mallory · Irvine · eight porters", summary:"The pair continue upward. Four porters accompany them toward Camp VI while the others return with messages for expedition leader Edward Norton.", source:"Expedition porter reports" },
  { id:"note", date:"7 Jun 1924", sort:"1924-06-07T16:00", time:"Late afternoon", title:"Mallory’s final note", altitude:"c. 8,170 m", camp:"Camp VI", type:"document", certainty:"documented", people:"Mallory · John Noel", summary:"Mallory asks photographer John Noel to watch for them on the skyline at 8 a.m.; he notes that they will probably start early and that the weather looks perfect.", source:"Mallory note, RGS collection" },
  { id:"departure", date:"8 Jun 1924", sort:"1924-06-08T05:30", time:"Estimated 05:00–06:00", title:"Summit attempt begins", altitude:"c. 8,170 m", camp:"Camp VI", type:"inference", certainty:"estimated", people:"Mallory · Irvine", summary:"No one witnesses their departure. Oxygen calculations, their camp position and later sightings suggest an early start, but the exact time is unknown.", source:"Reconstruction from expedition evidence" },
  { id:"noel", date:"8 Jun 1924", sort:"1924-06-08T08:00", time:"08:00", title:"Noel watches the skyline", altitude:"View from above Camp III", camp:"Photographic lookout", type:"testimony", certainty:"documented", people:"John Noel · two porters", summary:"Noel is in position with a telescopic camera as requested, but cloud and distance prevent a confirmed sighting or usable summit film.", source:"1924 expedition accounts" },
  { id:"odell", date:"8 Jun 1924", sort:"1924-06-08T12:50", time:"12:50", title:"The last confirmed sighting", altitude:"c. 8,500–8,600 m", camp:"Northeast ridge", type:"testimony", certainty:"witnessed", people:"Noel Odell · Mallory · Irvine", summary:"During a sudden clearing, Odell sees two black dots moving toward and then over a prominent rock step. He later writes that they were “going strong for the top.” Which Step he saw remains disputed.", source:"Odell, Geographical Journal (1924)" },
  { id:"storm", date:"8 Jun 1924", sort:"1924-06-08T14:00", time:"c. 14:00", title:"Snow squall closes the view", altitude:"c. 8,170 m", camp:"Camp VI", type:"testimony", certainty:"documented", people:"Noel Odell", summary:"Odell reaches Camp VI amid worsening weather, finds spare gear inside, whistles and shouts into the storm, then descends to Camp IV without seeing the pair return.", source:"Odell’s 1924 account" },
  { id:"signals", date:"8 Jun 1924", sort:"1924-06-08T16:30", time:"Late afternoon", title:"Six crosses signal no news", altitude:"c. 7,010 m", camp:"Camp IV", type:"document", certainty:"documented", people:"Noel Odell · lower camps", summary:"Odell lays out sleeping bags in the agreed signal: six crosses, meaning no trace of Mallory and Irvine. The message is observed from below.", source:"The Fight for Everest (1924)" },
  { id:"search", date:"9–10 Jun 1924", sort:"1924-06-09T08:00", time:"Two-day search", title:"Odell searches the high camps", altitude:"to c. 8,170 m", camp:"Camps V and VI", type:"testimony", certainty:"documented", people:"Noel Odell", summary:"Odell returns upward. On 10 June he finds Camp VI as he left it: the climbers have not returned. The expedition accepts that they are lost.", source:"Merton College / RGS timeline" },
  { id:"axe", date:"1933", sort:"1933-05-30T12:00", time:"Expedition season", title:"Irvine’s ice axe is found", altitude:"c. 8,460 m", camp:"Below First Step", type:"artifact", certainty:"documented", people:"Percy Wyn-Harris", summary:"An ice axe, later identified by characteristic markings as Irvine’s, is found on slabs below the northeast ridge. Whether it marks an accident site or was deliberately placed is unknown.", source:"1933 British Everest expedition" },
  { id:"bottle", date:"1991", sort:"1991-05-01T12:00", time:"Expedition season", title:"1924 oxygen cylinder recovered", altitude:"c. 8,475 m", camp:"Near First Step", type:"artifact", certainty:"documented", people:"Eric Simonson expedition", summary:"A 1924 oxygen bottle is located below the First Step. Its position helps researchers model the pair’s pace, oxygen use and possible route.", source:"Mallory & Irvine research chronology" },
  { id:"body", date:"1 May 1999", sort:"1999-05-01T11:45", time:"11:45", title:"Mallory is found", altitude:"c. 8,155 m", camp:"North Face snow terrace", type:"artifact", certainty:"documented", people:"Conrad Anker · search team", summary:"Mallory’s body and personal effects are found well below the ridge. Injuries and a rope mark indicate a serious fall while roped, but do not establish whether it occurred before or after a summit.", source:"1999 Mallory & Irvine Research Expedition" },
  { id:"irvine", date:"Sep 2024", sort:"2024-09-15T12:00", time:"Expedition season", title:"Evidence of Irvine emerges from the glacier", altitude:"Central Rongbuk Glacier", camp:"Below North Face", type:"artifact", certainty:"probable", people:"National Geographic team", summary:"A boot and sock bearing Irvine’s name are found on the Central Rongbuk Glacier. The find is believed to be his; DNA comparison was proposed. It does not resolve the summit question or locate the camera.", source:"National Geographic / AP, October 2024" }
];

window.MALLORY_CAMPS = [
  {id:"base", label:"Base Camp", altitude:5150, x:10, y:88, focus:"50% 90%", description:"Rongbuk Base Camp was the expedition’s logistical anchor at the foot of Everest’s northern approaches."},
  {id:"camp3", label:"Camp III", altitude:6400, x:28, y:73, focus:"43% 72%", description:"Advanced Base Camp stood beyond the East Rongbuk Glacier, below the steep ascent to the North Col."},
  {id:"camp4", label:"Camp IV · North Col", altitude:7010, x:43, y:59, focus:"30% 58%", description:"The North Col formed the gateway to the exposed north ridge and the starting point of the final high-camp push."},
  {id:"camp5", label:"Camp V", altitude:7680, x:58, y:45, focus:"46% 44%", description:"Camp V occupied the wind-scoured ridge. Porters supported Mallory and Irvine here on 7 June."},
  {id:"camp6", label:"Camp VI", altitude:8170, x:69, y:34, focus:"57% 34%", description:"The tiny final camp was the pair’s last known shelter before their summit attempt on 8 June 1924."},
  {id:"step1", label:"First Step", altitude:8564, x:79, y:24, focus:"65% 25%", description:"The first major rock step rises from the northeast ridge; a 1924 oxygen cylinder was later found nearby."},
  {id:"step2", label:"Second Step", altitude:8610, x:85, y:18, focus:"72% 17%", description:"The steep Second Step is the route’s technical crux and central to debate over Odell’s final sighting."},
  {id:"summit", label:"Summit", altitude:8849, x:94, y:8, focus:"49% 7%", description:"The summit was Mallory and Irvine’s objective, but no surviving evidence confirms that they reached it."}
];
